#!/usr/bin/env node

'use strict';

var program = require('commander'),
    request = require('request'),
    util = require('util'),
    i,
    url,
    message;

program
    .version('0.0.1')
    .option('-H, --host [hostname]', 'host, \'localhost\' by default', 'localhost')
    .option('-P, --port [number]', 'port, 3001 by default', 3000, parseInt)
    .option('-S, --service [name]', 'service, \'testing\' by default', 'testing')
    .option('-M, --message [text]', 'message content', 'Hello World!\n')
    .option('-X, --secure', 'use HTTPS', false)
    .parse(process.argv);
url = util.format('%s://%s:%d/message', program.secure ? 'https' : 'http', program.host, program.port);
message = {
  'content': program.message,
};
console.log('url\n', url);
console.log('message\n', message);
request.post({url: url, json: message}, function (err, res, body) {
  if (err) {
    console.log('error\n', err);
  }
  else {
    console.log('statusCode\n', res.statusCode);
    console.log('headers\n', res.headers);
    console.log('body\n', body);
  }
});
function range(val) {
  return val.split('..').map(Number);
}
function list(val) {
  return val.split(',');
}

